spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: miscroservicecloud-config-dev
---
spring:
  profiles: test
  application:
    name: miscroservicecloud-config-test